"""added is_analysed column

Revision ID: 638366a8d7d2
Revises: 4e1379900640
Create Date: 2023-04-04 11:38:57.807047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '638366a8d7d2'
down_revision = '4e1379900640'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_analysed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site', schema=None) as batch_op:
        batch_op.drop_column('is_analysed')

    # ### end Alembic commands ###
