"""Updated Analytics table

Revision ID: 6d7cddc720f7
Revises: aefd41aaed9b
Create Date: 2023-04-05 14:08:17.688204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d7cddc720f7'
down_revision = 'aefd41aaed9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analytics', schema=None) as batch_op:
        batch_op.drop_column('solar_power_output')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analytics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('solar_power_output', sa.FLOAT(), nullable=True))

    # ### end Alembic commands ###
