"""Added analytics table

Revision ID: aefd41aaed9b
Revises: 638366a8d7d2
Create Date: 2023-04-04 17:21:42.955586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aefd41aaed9b'
down_revision = '638366a8d7d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics',
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('solar_power', sa.Float(), nullable=True),
    sa.Column('solar_power_output', sa.Float(), nullable=True),
    sa.Column('breakeven', sa.Float(), nullable=True),
    sa.Column('carbonfootprint', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analytics')
    # ### end Alembic commands ###
